### ISSUE TITLE
Consider some kind of defaulted unclassified property type

### ISSUE THREAD

**Issue by andzandz** [ifp/schemas#11]
# See my final comment at the end of the page

Adverts can have type _unclassified either:

1. The property type in the feed does exist in the template but we cannot map it to anything sensible, like "property" or "building"

2. The property type in the feed is not listed in the template, so the Importer has defaulted it to _unclassified

In the Checker I would like to be able to tell these apart as a clue that we should look at improving the property type mappings in the template

**Comment by andzandz** [comment]
perhaps

"_unknown": enum was not recognised
"_unclassified": to map a known value that we cannot classify e.g. "property", "building"

although they sound quite similar

**Comment by ifpingram** [comment]
happy with whatever you want to go with :)

**Comment by andzandz** [comment]
Do we have any logic that relies on property.attributes.types being an array? Conflicts in Loader?

Perhaps an empty array

**Comment by ifpingram** [comment]
Will be as per schema, which is GOD regards what we can and cannot do:

```yaml
"types": {
              "type": "array",
              "items": {
                "type": [
                  "string"
                ],
                "enum": [
                  "_unclassified",
                  "residential",
                  "business",
                  "apartment",
                  "apartment_building",
                  "bar",
                  "barn",
                  "bed_and_breakfast",
                  "cafe",
                  "campsite",
                  "chateau",
                  "farm",
                  "gite",
                  "gite_complex",
                  "hotel",
                  "house",
                  "house_boat",
                  "lake",
                  "land",
                  "mobile_home",
                  "office",
                  "restaurant",
                  "shop",
                  "vineyard"
                ]
              },
              "minItems": 0,
              "uniqueItems": true
            },
```

So, as it is min items 0, we can have empty array.

**Comment by ifpingram** [comment]
I presume this can be done in Importer. Give it a test. If it doesn't submit a priority bug for Dan please.

Thanks

**Comment by andzandz** [comment]
As it is an array, we can use multiple types

A recognised value which we cannot classify:
["_unclassified"]

An property type unrecognised by Importer:
["_unclassified", "_unmapped"]

**Comment by ifpingram** [comment]
https://raw.githubusercontent.com/ifp/schemas/master/json/internal/property/enums/types-schema-enum.json
