### ISSUE TITLE
Limit length of advert titles? Old system does this

### ISSUE THREAD

**Issue by andzandz** [ifp/schemas#21]
![image](https://cloud.githubusercontent.com/assets/13456494/25620954/e87a199c-2f47-11e7-8944-d7db9e162afa.png)

https://develop.lakesfrance.com/sale-property/1252-FP-74618JK17

**Comment by ifpingram** [comment]
This is handled in loader, as we do not want to invalidate adverts because of long titles, but instead trim them down on loading...

https://github.com/ifp/service_loader.french-property.com/issues/86
