### ISSUE TITLE
Schema wishlist Feb 2017

### ISSUE THREAD

**Issue by andzandz** [ifp/schemas#9]
- Add some way to handle rentals so I can map feeds to use it - e.g. "tenure" field value - we could also consider price_freqency i.e. weekly/monthly

Attributes:
- Add "view" tag
- "vineyard" is a type only - make it both a type and a feature, like lake
- Add "leisure facilities" feature - for lakes with jetties, piers and such, but depends on the type, or we could just add water_leisure_facilities as we have tennis_court etc already
- "mill" should be a type, not a tag
- add "studio_apartment" tag and get Loader to auto-apply when type=apartment and bedrooms=0

**Comment by ifpingram** [comment]
No rentals for now as per discussion.

**Comment by ifpingram** [comment]
"view" is too subjective and open to gaming by agents.

**Comment by ifpingram** [comment]
vineyard is now a type and a feature

**Comment by ifpingram** [comment]
"leisure facilities" too subjective and open ended.

**Comment by ifpingram** [comment]
"mill" is too niche for property types which we are keeping broad, hence why it remains as a Type.

**Comment by ifpingram** [comment]
"studio_apartment" is handled in the front end.
